import 'package:cached_network_image/cached_network_image.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:intl/intl.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:health_vista_pro/bloc/blocs.dart';
import 'package:health_vista_pro/models/models.dart' as m;
import 'package:health_vista_pro/pages/pages.dart';
import 'package:health_vista_pro/services/services.dart';
import 'package:health_vista_pro/shared/shared.dart';

part 'rounded_btn.dart';
part 'doctor_card.dart';
// part 'custom_app_bar.dart';
part 'custom_chat_tile.dart';
part 'cached_image.dart';
part 'quiet_box.dart';
part 'user_photo.dart';
part 'contact_view.dart';
part 'last_message_container.dart';
part 'online_dot_indicator.dart';
part 'my_appointments_list.dart';
